---
- name: Install key
  become: true
  apt_key:
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present

- name: Install repo
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    filename: google-chrome
    state: present

- name: Install
  become: true
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: true